# Generated by Django 5.2.6 on 2025-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewmodel",
            name="rating",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
