# Generated by Django 5.2.6 on 2025-09-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_reviewmodel_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewmodel",
            name="rating",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
