# Generated by Django 5.2.6 on 2025-09-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_alter_reviewmodel_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewmodel",
            old_name="your_review",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="reviewmodel",
            old_name="review_title",
            new_name="title",
        ),
    ]
