# Generated by Django 5.2.6 on 2025-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_rename_your_review_reviewmodel_body_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewmodel",
            options={"ordering": ["-added_at"]},
        ),
        migrations.AlterField(
            model_name="reviewmodel",
            name="author",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="reviewmodel",
            name="body",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reviewmodel",
            name="rating",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="reviewmodel",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
