# Generated by Django 5.2.6 on 2025-09-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0005_alter_reviewmodel_options_alter_reviewmodel_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewmodel",
            options={},
        ),
    ]
