# Generated by Django 5.2.6 on 2025-09-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0006_alter_reviewmodel_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewmodel",
            name="edited_at",
        ),
    ]
