# Generated by Django 5.2.6 on 2025-09-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0007_remove_reviewmodel_edited_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewmodel",
            old_name="added_at",
            new_name="createdAt",
        ),
    ]
